name: Build website
on:
  pull_request:
    branches: [master]
    paths:
      - "website/**"
      - "firebase.json"
      - ".github/workflows/*-website.yml"
  push:
    branches: [master]
    paths:
      - "website/**"
      - "firebase.json"
      - ".github/workflows/*-website.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PR_INFO_FILE: ".PR_INFO"
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Build
        run: |
          cd website
          npm install
          npm run build

      # this won't delete existing translation and will only add new ones
      - name: Generate Stubs for in-code Localization
        if: github.event_name == 'pull_request'
        run: |
          cd website
          npm run write-translations

      # in case of follow-up commits during the build
      - run: git pull
        if: github.event_name == 'pull_request'

      # this will only commit when the generated stubs are different
      - name: Commit Localization
        if: github.event_name == 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "🤖 Append stubs for in-code localization"

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: website/build/
          retention-days: 1

      - if: github.event_name == 'pull_request'
        name: Build pr info
        run: |
          echo "${{ github.event.number }}" > $PR_INFO_FILE

      - if: github.event_name == 'pull_request'
        name: Upload pr info
        uses: actions/upload-artifact@v2
        with:
          name: pr-info
          path: "${{ env.PR_INFO_FILE }}"
          retention-days: 1
